### ISSUE TITLE
Objects in the cache expires even though eternal is set to true.

### ISSUE THREAD

**Issue by slaborde** [smparekh/camel-cache-example#1]
Objects in the cache expires even though eternal is set to true. When a new element is added to the cache its properties are set to its default values. dont know why such behaivour

The solution i found, was to also put the cache properties into the route itself (see below, bolded text), do you have a better solution ??

// CXFRS Entry Point
        from("cxfrs:bean:rsServer?bindingStyle=SimpleConsumer")
            .log("GET Request Received...")
            .choice()
                .when(header("operationName").isEqualTo("addEntry"))
                    .log("In add entry choice")
                    .log("${headers}")
                    .to("bean:restImplBean?method=addEntry")
                    **.to("cache://MyApplicationCache?eternal=true")**
                    .to("bean:restImplBean?method=addedEntry")
                .when(header("operationName").isEqualTo("getEntry"))
                    .log("In get entry choice")
                    .to("bean:restImplBean?method=getEntry")
                    .to("cache://MyApplicationCache")
                    .log("${headers}")
                    .choice()
                        .when(header(CacheConstants.CACHE_ELEMENT_WAS_FOUND).isNull())
                        .to("bean:restImplBean?method=notFound")
                        .otherwise()
                        .to("bean:restImplBean?method=gotEntry")
                    .end()
            .end();

**Comment by smparekh** [comment]
I believe if you are including it every time you access the cache you might be recreating the cache with those properties (hence why its working). How do you know the cache items are expiring?

**Comment by slaborde** [comment]
Because i execute addEntry and after aprox 10 min idle, when i execute getEntry again the value is not found in the cache anymore... including the properties every time seems it works, the elements never expires..

I tested it, and the cache is not re-created or at least all the elements still there. I mean, i add several items, and all of them still in the cache after the last one was added, so i think the cache is not recreated every time i access it.

But of course, if you can check it by yourself and give me your feedback..

**Comment by smparekh** [comment]
Unfortunately, I can't currently check it. I would suggest testing it with the newest version of Camel and if the bug still persists open up a bug on the Camel Jira.

If you don't care to include the properties everytime you can do the following:

```
@PropertyInject("cacheConfig")
String cacheConfig;
```

replace all instances of
`.to("cache://myAppCache?options")` -> `.to(cacheConfig)`

in your property file:
`cacheConfig = cache://myAppCache?options`

**Comment by slaborde** [comment]
I will do that, thank you very much for your response.
